---
- name: configure network devices
  hosts: rtr1,rtr2
  gather_facts: false
  tasks:
    - name: gather router facts
      ios_facts:
        gather_subset: interfaces
        gather_network_resources: interfaces

    - name: configure device with config
      cli_config:
        config: "{{ lookup('template', 'template.j2') }}"

    - name: configure device NAT with config
      cli_config:
        config: "{{ lookup('template', 'template-ir829.j2') }}"
      when: ansible_net_model == "IR829GW-LTE-GA-ZK9"

    - name: configure device NAT with config
      cli_config:
        config: "{{ lookup('template', 'template-ir809.j2') }}"
      when: ansible_net_model == "IR809G-LTE-GA-K9"

