---
- name: gather information from routers
  hosts: routers
  gather_facts: no

  tasks:
    - name: gather router facts
      ios_facts:

    - name: Run cli_command on Cisco IOS and display results
      block:
        - name: Run cli_command on Cisco IOS
          ios_command:
            commands: show ip int br
          register: result

        - name: Display result to terminal window
          debug:
            var: result.stdout_lines
      when: ansible_net_iostype  == 'IOS'

    - name: print
      debug:
         msg:  "{{item.value.ipv4[0].address}}"
      loop:  "{{ hostvars[inventory_hostname].ansible_net_interfaces | dict2items  }}"
      when: item.value.ipv4[0] is defined
      loop_control:
        label: "Endereço IP" 
      run_once: true


